use std::collections::HashMap;

pub struct ChampionData {
    champions: HashMap<u64, String>,
}

impl ChampionData {
    pub fn new() -> Self {
        let mut champions = HashMap::new();
        // Add all champion IDs and names here
        champions.insert(266, "Aatrox".to_string());
        champions.insert(103, "Ahri".to_string());
        champions.insert(84, "Akali".to_string());
        champions.insert(166, "Akshan".to_string());
        champions.insert(12, "Alistar".to_string());
        champions.insert(32, "Amumu".to_string());
        champions.insert(34, "Anivia".to_string());
        champions.insert(1, "Annie".to_string());
        champions.insert(523, "Aphelios".to_string());
        champions.insert(22, "Ashe".to_string());
        champions.insert(136, "Aurelion Sol".to_string());
        champions.insert(893, "Aurora".to_string());
        champions.insert(268, "Azir".to_string());
        champions.insert(432, "Bard".to_string());
        champions.insert(200, "Bel'Veth".to_string());
        champions.insert(53, "Blitzcrank".to_string());
        champions.insert(63, "Brand".to_string());
        champions.insert(201, "Braum".to_string());
        champions.insert(233, "Briar".to_string());
        champions.insert(51, "Caitlyn".to_string());
        champions.insert(164, "Camille".to_string());
        champions.insert(69, "Cassiopeia".to_string());
        champions.insert(31, "Cho'Gath".to_string());
        champions.insert(42, "Corki".to_string());
        champions.insert(122, "Darius".to_string());
        champions.insert(131, "Diana".to_string());
        champions.insert(119, "Draven".to_string());
        champions.insert(36, "Dr. Mundo".to_string());
        champions.insert(245, "Ekko".to_string());
        champions.insert(60, "Elise".to_string());
        champions.insert(28, "Evelynn".to_string());
        champions.insert(81, "Ezreal".to_string());
        champions.insert(9, "Fiddlesticks".to_string());
        champions.insert(114, "Fiora".to_string());
        champions.insert(105, "Fizz".to_string());
        champions.insert(3, "Galio".to_string());
        champions.insert(41, "Gangplank".to_string());
        champions.insert(86, "Garen".to_string());
        champions.insert(150, "Gnar".to_string());
        champions.insert(79, "Gragas".to_string());
        champions.insert(104, "Graves".to_string());
        champions.insert(887, "Gwen".to_string());
        champions.insert(120, "Hecarim".to_string());
        champions.insert(74, "Heimerdinger".to_string());
        champions.insert(910, "Hwei".to_string());
        champions.insert(420, "Illaoi".to_string());
        champions.insert(39, "Irelia".to_string());
        champions.insert(427, "Ivern".to_string());
        champions.insert(40, "Janna".to_string());
        champions.insert(59, "Jarvan IV".to_string());
        champions.insert(24, "Jax".to_string());
        champions.insert(126, "Jayce".to_string());
        champions.insert(202, "Jhin".to_string());
        champions.insert(222, "Jinx".to_string());
        champions.insert(145, "Kai'Sa".to_string());
        champions.insert(429, "Kalista".to_string());
        champions.insert(43, "Karma".to_string());
        champions.insert(30, "Karthus".to_string());
        champions.insert(38, "Kassadin".to_string());
        champions.insert(55, "Katarina".to_string());
        champions.insert(10, "Kayle".to_string());
        champions.insert(141, "Kayn".to_string());
        champions.insert(85, "Kennen".to_string());
        champions.insert(121, "Kha'Zix".to_string());
        champions.insert(203, "Kindred".to_string());
        champions.insert(240, "Kled".to_string());
        champions.insert(96, "Kog'Maw".to_string());
        champions.insert(897, "K'Sante".to_string());
        champions.insert(7, "LeBlanc".to_string());
        champions.insert(64, "Lee Sin".to_string());
        champions.insert(89, "Leona".to_string());
        champions.insert(876, "Lillia".to_string());
        champions.insert(127, "Lissandra".to_string());
        champions.insert(236, "Lucian".to_string());
        champions.insert(117, "Lulu".to_string());
        champions.insert(99, "Lux".to_string());
        champions.insert(54, "Malphite".to_string());
        champions.insert(90, "Malzahar".to_string());
        champions.insert(57, "Maokai".to_string());
        champions.insert(11, "Master Yi".to_string());
        champions.insert(902, "Milio".to_string());
        champions.insert(21, "Miss Fortune".to_string());
        champions.insert(62, "Wukong".to_string());
        champions.insert(82, "Mordekaiser".to_string());
        champions.insert(25, "Morgana".to_string());
        champions.insert(950, "Naafiri".to_string());
        champions.insert(267, "Nami".to_string());
        champions.insert(75, "Nasus".to_string());
        champions.insert(111, "Nautilus".to_string());
        champions.insert(518, "Neeko".to_string());
        champions.insert(76, "Nidalee".to_string());
        champions.insert(895, "Nilah".to_string());
        champions.insert(56, "Nocturne".to_string());
        champions.insert(20, "Nunu & Willump".to_string());
        champions.insert(2, "Olaf".to_string());
        champions.insert(61, "Orianna".to_string());
        champions.insert(516, "Ornn".to_string());
        champions.insert(80, "Pantheon".to_string());
        champions.insert(78, "Poppy".to_string());
        champions.insert(555, "Pyke".to_string());
        champions.insert(246, "Qiyana".to_string());
        champions.insert(133, "Quinn".to_string());
        champions.insert(497, "Rakan".to_string());
        champions.insert(33, "Rammus".to_string());
        champions.insert(421, "Rek'Sai".to_string());
        champions.insert(526, "Rell".to_string());
        champions.insert(888, "Renata Glasc".to_string());
        champions.insert(58, "Renekton".to_string());
        champions.insert(107, "Rengar".to_string());
        champions.insert(92, "Riven".to_string());
        champions.insert(68, "Rumble".to_string());
        champions.insert(13, "Ryze".to_string());
        champions.insert(360, "Samira".to_string());
        champions.insert(113, "Sejuani".to_string());
        champions.insert(235, "Senna".to_string());
        champions.insert(147, "Seraphine".to_string());
        champions.insert(875, "Sett".to_string());
        champions.insert(35, "Shaco".to_string());
        champions.insert(98, "Shen".to_string());
        champions.insert(102, "Shyvana".to_string());
        champions.insert(27, "Singed".to_string());
        champions.insert(14, "Sion".to_string());
        champions.insert(15, "Sivir".to_string());
        champions.insert(72, "Skarner".to_string());
        champions.insert(901, "Smolder".to_string());
        champions.insert(37, "Sona".to_string());
        champions.insert(16, "Soraka".to_string());
        champions.insert(50, "Swain".to_string());
        champions.insert(517, "Sylas".to_string());
        champions.insert(134, "Syndra".to_string());
        champions.insert(223, "Tahm Kench".to_string());
        champions.insert(163, "Taliyah".to_string());
        champions.insert(91, "Talon".to_string());
        champions.insert(44, "Taric".to_string());
        champions.insert(17, "Teemo".to_string());
        champions.insert(412, "Thresh".to_string());
        champions.insert(18, "Tristana".to_string());
        champions.insert(48, "Trundle".to_string());
        champions.insert(23, "Tryndamere".to_string());
        champions.insert(4, "Twisted Fate".to_string());
        champions.insert(29, "Twitch".to_string());
        champions.insert(77, "Udyr".to_string());
        champions.insert(6, "Urgot".to_string());
        champions.insert(110, "Varus".to_string());
        champions.insert(67, "Vayne".to_string());
        champions.insert(45, "Veigar".to_string());
        champions.insert(161, "Vel'Koz".to_string());
        champions.insert(711, "Vex".to_string());
        champions.insert(254, "Vi".to_string());
        champions.insert(234, "Viego".to_string());
        champions.insert(112, "Viktor".to_string());
        champions.insert(8, "Vladimir".to_string());
        champions.insert(106, "Volibear".to_string());
        champions.insert(19, "Warwick".to_string());
        champions.insert(498, "Xayah".to_string());
        champions.insert(101, "Xerath".to_string());
        champions.insert(5, "Xin Zhao".to_string());
        champions.insert(157, "Yasuo".to_string());
        champions.insert(777, "Yone".to_string());
        champions.insert(83, "Yorick".to_string());
        champions.insert(350, "Yuumi".to_string());
        champions.insert(154, "Zac".to_string());
        champions.insert(238, "Zed".to_string());
        champions.insert(221, "Zeri".to_string());
        champions.insert(115, "Ziggs".to_string());
        champions.insert(26, "Zilean".to_string());
        champions.insert(142, "Zoe".to_string());
        champions.insert(143, "Zyra".to_string());

        ChampionData { champions }
    }

    pub fn get_name(&self, id: u64) -> String {
        self.champions.get(&id).cloned().unwrap_or_else(|| format!("Champion{}", id))
    }
}